# style.py

# Define some style variables and their values
BACKGROUND_COLOR = "#f0f0f0"
FOREGROUND_COLOR = "#333333"
FONT = "Arial"
MAIN_LABEL_FONT_SIZE = 36
FONT_SIZE = 12
BUTTON_COLOR = "#4CAF50"
BUTTON_TEXT_COLOR = "#FFFFFF"
ENTRY_BORDER_COLOR = "#CCCCCC"
ENTRY_BACKGROUND_COLOR = "#FFFFFF"
LABEL_FONT = (FONT, FONT_SIZE)
BUTTON_FONT = (FONT, FONT_SIZE, "bold")

# Additional color variables
BLUE = "#2196F3"
AMBER = "#FFC107"
GREEN = "#4CAF50"
RED = "#F44336"
YELLOW = "#FFEB3B"
CYAN = "#00BCD4"
LIGHT_GRAY = "#F8F9FA"
DARK_GRAY = "#343A40"
BLACK = "#1F1F1F"
WHITE = "#F2F2F2"